version: '3.4'

services:
  dotnetlibrarymanagementwebapi:
    image: ${DOCKER_REGISTRY-}dotnetlibrarymanagementwebapi
    build:
      context: .
      dockerfile: LibraryManagementAdministrationWebApi/Dockerfile
